Sun Feb 22 11:39:44 PM WIB 2026

diff --git a/src/function/install_ubuntu b/src/function/install_ubuntu
--- a/src/function/install_ubuntu
+++ b/src/function/install_ubuntu
@@ -46,6 +46,14 @@ INSTALL_UBUNTU () {
 	printf "ubuntu" > $ROOT/etc/hostname
 	echo "PS1='\W \\$ ' " >> $ROOT/root/.bashrc
 	echo 'cd $HOME' >> $ROOT/etc/bash.bashrc
+    EXEC "apt update" || {
+        printf "install error: failed to update package list.\n"
+        printf "try to update manually.\n"
+    }
+    EXEC "apt upgrade -y" || {
+        printf "install error: failed to upgrade packages.\n"
+        printf "try to upgrade manually.\n"
+    }
     printf "$(basename $0): Ubuntu installed.\n"
     return 1
 }
